"""Updated schemas __init__.py with all schemas."""

from app.schemas.container import (
    ContainerActionRequest,
    ContainerActionResponse,
    ContainerBase,
    ContainerCreate,
    ContainerDetailResponse,
    ContainerGroupBase,
    ContainerGroupCreate,
    ContainerGroupListResponse,
    ContainerGroupResponse,
    ContainerGroupUpdate,
    ContainerListResponse,
    ContainerLogsResponse,
    ContainerResponse,
    ContainerStatsResponse,
    ContainerUpdate,
)
from app.schemas.docker_compose import (
    DockerComposeProjectResponse,
    DockerComposePullResponse,
    DockerComposeServiceResponse,
)
from app.schemas.response import (
    BaseResponse,
    ContainerStatus,
    DataResponse,
    ErrorResponse,
    OperationStatus,
    PaginatedResponse,
    PaginationParams,
    ResponseModel,
    TokenResponse,
    create_paginated_response,
)
from app.schemas.stats import (
    ContainerStatsHistoryResponse,
    DashboardStatsResponse,
    ResourceUsageResponse,
    SystemStatsHistoryResponse,
    SystemStatsResponse,
)
from app.schemas.user import (
    CurrentUserResponse,
    LoginResponse,
    LogoutResponse,
    RefreshTokenRequest,
    TokenPayload,
    TokenRefreshResponse,
    UserBase,
    UserCreate,
    UserListResponse,
    UserLogin,
    UserPasswordUpdate,
    UserResponse,
    UserUpdate,
)


__all__ = [
    # User schemas
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserPasswordUpdate",
    "UserResponse",
    "UserListResponse",
    "UserLogin",
    "TokenPayload",
    "RefreshTokenRequest",
    "LoginResponse",
    "LogoutResponse",
    "TokenRefreshResponse",
    "CurrentUserResponse",
    # Response schemas
    "BaseResponse",
    "DataResponse",
    "PaginatedResponse",
    "ResponseModel",
    "TokenResponse",
    "ErrorResponse",
    "PaginationParams",
    "ContainerStatus",
    "OperationStatus",
    "create_paginated_response",
    # Container schemas
    "ContainerBase",
    "ContainerCreate",
    "ContainerUpdate",
    "ContainerResponse",
    "ContainerDetailResponse",
    "ContainerStatsResponse",
    "ContainerLogsResponse",
    "ContainerActionRequest",
    "ContainerActionResponse",
    "ContainerListResponse",
    "ContainerGroupBase",
    "ContainerGroupCreate",
    "ContainerGroupUpdate",
    "ContainerGroupResponse",
    "ContainerGroupListResponse",
    # Stats schemas
    "SystemStatsResponse",
    "SystemStatsHistoryResponse",
    "DashboardStatsResponse",
    "ContainerStatsHistoryResponse",
    "ResourceUsageResponse",
    # Docker Compose schemas
    "DockerComposeProjectResponse",
    "DockerComposePullResponse",
    "DockerComposeServiceResponse",
]
